repos:
  - repo: local
    hooks:
      - id: Black formatting
        language: system
        name: Formatting
        entry: poetry run black {{cookiecutter.project_slug}} tests
        files: .py
        stages: [ commit ]
      - id : Isort formatting
        language: system
        name: Formatting
        entry: poetry run isort {{cookiecutter.project_slug}} tests
        files: .py
        stages: [ commit ]
