# Title of the site
site_name: Pypate

# Description of the site
site_description: Docs for the python-package-template

# URL for pages editing
repo_url: https://github.com/deknowny/python-package-template

# Branch chosen when routing to repository
remote_branch: gh-pages

# Site's content
nav:
  - Home: index.md
  - Step-by-step User Guide:
    - Introduction: user-guide/index.md
    - First init: user-guide/first-init.md
    - About Makefile: user-guide/makefile.md
    - About Poetry: user-guide/poetry.md
    - About environments and virtaulenv: user-guide/environments.md
    - Formatters: user-guide/formatters.md
    - Linters: user-guide/linters.md
  - Reference:
    - Introduction: reference/index.md
    - Manage dependencies: reference/manage-dependencies.md
    - About vendor dependencies: reference/vendor.md


# Theme preference. Use `mkdocs-material`
theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Monaco
  features:
    - header.autohide

extra_css:
  - stylesheets/slate.css

# Material extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra:
  version:
    provider: mike
    default: latest
