# Title of the site
site_name: Docs | python-package-template

# Description of the site
site_description: Docs for the python-package-template

# URL for pages editing
repo_url: https://github.com/python-package-template/tree/main

# Branch chosen when routing to repository
remote_branch: gh-pages

# Site's content
nav:
  - Home: index.md


# Theme preference. Use `mkdocs-material`
theme:
  name: material
  font:
    text: Ubuntu
    code: Monaco
  features:
    - header.autohide
#    palette:
#      scheme: slate
#      accent: amber

# Material extensions
markdown_extensions:
  - admonition
