# Title of the site
site_name: Pypate

# Description of the site
site_description: Docs for the python-package-template

# URL for pages editing
repo_url: https://github.com/python-package-template

# Branch chosen when routing to repository
remote_branch: gh-pages

# Site's content
nav:
  - Home: index.md


# Theme preference. Use `mkdocs-material`
theme:
  name: material
  palette:
    - scheme: default
      primary: brown
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Monaco
  features:
    - header.autohide
#    palette:
#      scheme: slate
#      accent: amber

# Material extensions
markdown_extensions:
  - admonition
