name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: make install-docs
        name: Install mkdocs dependencies
      - run: make deploy-docs
        name: Build docs
